Produccion/Produccion/Models/RawMaterialViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;

namespace Produccion.Models
{
    public class RawMaterialViewModel
    {
        public int Id { get; set; }
        [Display(Name = "Nombre")]
        [Required]
        public string Nombre { get; set; }
        [Display(Name = "Color")]
        public int ColorId { get; set; }
        public IEnumerable<SelectListItem>? Colors { get; set; }
        [Display(Name = "Tipo de Tela")]
        public int FabricId { get; set; }
        public IEnumerable<SelectListItem>? Fabrics { get; set; }

    }
}

Produccion/Produccion/Controllers/RawMaterialsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Produccion.Data;
using Produccion.Data.Entities;
using Produccion.Helpers;
using Produccion.Models;
using Vereyon.Web;
using static Produccion.Helpers.ModalHelper;

namespace Produccion.Controllers
{
    public class RawMaterialsController : Controller
    {
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IFlashMessage _flashMessage;

        public RawMaterialsController(DataContext context, ICombosHelper combosHelper, IFlashMessage flashMessage)
        {
            _context = context;
            _combosHelper = combosHelper;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.RawMaterials
                .Include(r => r.Color)
                .Include(r => r.Fabric)
                .ToListAsync());
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id)
        {
            RawMaterialViewModel model = new()
            {
                Colors = await _combosHelper.GetComboColorsAsync(),
                Fabrics = await _combosHelper.GetComboFabricsAsync(),
            };
            if (id == 0)
            {
                return View(model);
            }
            else
            {
                RawMaterial rawMaterial = await _context.RawMaterials
                .Include(r => r.Color)
                .Include(r => r.Fabric)
                .FirstOrDefaultAsync(r => r.Id == id);

                model = new()
                {
                    Id = rawMaterial.Id,
                    Nombre = rawMaterial.Nombre,
                    Colors = await _combosHelper.GetComboColorsAsync(),
                    ColorId = rawMaterial.Color.Id,
                    Fabrics = await _combosHelper.GetComboFabricsAsync(),
                    FabricId = rawMaterial.Fabric.Id
                };

                return View(model);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, RawMaterialViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (id == 0)
                    {
                        RawMaterial rawMaterial = new()
                        {
                            Nombre = model.Nombre,
                            Color = await _context.Colors.FindAsync(model.ColorId),
                            Fabric = await _context.Fabrics.FindAsync(model.FabricId),
                        };
                        _context.Add(rawMaterial);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro creado");
                    }
                    else
                    {
                        RawMaterial rawMaterial = new()
                        {
                            Id = model.Id,
                            Nombre = model.Nombre,
                            Color = await _context.Colors.FindAsync(model.ColorId),
                            Fabric = await _context.Fabrics.FindAsync(model.FabricId),
                        };
                        _context.Update(rawMaterial);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro actualizado");
                    }
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Danger("Ya existe un registro con el mismo nombre.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                    return View(model);
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                    return View(model);
                }
                model.Colors = await _combosHelper.GetComboColorsAsync();
                model.Fabrics = await _combosHelper.GetComboFabricsAsync();
                return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "Index", _context.RawMaterials.ToList()) });
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "AddOrEdit", model) });

        }
        
        [Authorize(Roles = "Admin")]
        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            RawMaterial rawMaterial = await _context.RawMaterials
                .Include(r => r.Inventories)
                .Include(r => r.ProductionOrders)
                .FirstOrDefaultAsync(r => r.Id == id);
            try
            {
                _context.RawMaterials.Remove(rawMaterial);
                await _context.SaveChangesAsync();
                _flashMessage.Info("Registro borrado.");

            }
            catch
            {
                _flashMessage.Danger("No se puede borrar el registro porque tiene datos relacionados.");

            }
            return RedirectToAction(nameof(Index));
        }  

    }
}

Produccion/Produccion/Views/RawMaterials/AddOrEdit.cshtml
@model Produccion.Models.RawMaterialViewModel

@{
    ViewData["Title"] = "Materia Prima";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <partial name="_RawMaterial"/>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-dark" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-dark"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Produccion/Produccion/Views/RawMaterials/Create.cshtml
@model Produccion.Models.RawMaterialViewModel

@{
    ViewData["Title"] = "Create";
}
<flash dismissable="true" />

<h1>Agregar Nueva Materia Prima</h1>


<hr />
<div class="row text-light">
    <div class="col-md-8">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <partial name="_RawMaterial"/>
            <div class="form-group mt-2">
                <input type="submit" value="Agregar" class="btn btn-dark" />
                <a asp-action="Index" class="btn btn-dark" >Regresar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Produccion/Produccion/Views/RawMaterials/Delete.cshtml
@model Produccion.Data.Entities.RawMaterial

@{
    ViewData["Title"] = "Delete";
}
<flash dismissable="true" />

<h1>Borrar color</h1>

<h3 class="text-light">¿Está seguro de querer borrar esta Materia prima?</h3>
<div class="text-light">
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> 
        <a asp-action="Index" class="btn btn-dark">Regresar</a>
    </form>
</div>

Produccion/Produccion/Views/RawMaterials/Edit.cshtml
@model Produccion.Models.RawMaterialViewModel

@{
    ViewData["Title"] = "Edit";
}
<flash dismissable="true" />

<h1>Editar Materia prima</h1>

<hr />
<div class="row text-light">
    <div class="col-md-8">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <partial name="_RawMaterial" />
            <div class="form-group mt-2">
                <input type="submit" value="Guardar" class="btn btn-dark" />
                <a asp-action="Index" class="btn btn-dark">Regresar</a>
            </div>

        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Produccion/Produccion/Views/RawMaterials/Index.cshtml
@model IEnumerable<Produccion.Data.Entities.RawMaterial>

@{
    ViewData["Title"] = "Index";
}
<flash dismissable="true" />




<div class="boton">
    <a onclick="showInPopup('@Url.Action("AddOrEdit", "RawMaterials", new { id = 0 }, Context.Request.Scheme)' , 'Agregar materia prima')" class="btn btn-dark mb-2" ><i class="fa-solid fa-circle-plus"></i> Materia Prima</a>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card bg-dark mb-3 " >
            <h3 class="panel-title text-light m-2"><i class="fa fa-earth-americas"></i> Materia Prima</h3>
            <div class="panel panel-default bg-light">            
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Color)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Fabric)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                @foreach (var item in Model) {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Color.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Fabric.Nombre)
                            </td>
                            <td>
                                <a onclick="showInPopup('@Url.Action("AddOrEdit", "RawMaterials", new { id=item.Id }, Context.Request.Scheme)' , 'Actualizar Materia Prima')" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square text-dark"></i> </a>
                                <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                            </td>
                        </tr>
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/RawMaterials/Delete/', false);
    </script>
}

Produccion/Produccion/Views/RawMaterials/_RawMaterial.cshtml
@model Produccion.Models.RawMaterialViewModel


    <div class="form-group">
        <span class="required">*</span>
        <label asp-for="Nombre" class="control-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>
    <div class="form-group">
        <span class="required">*</span>
        <label asp-for="ColorId" class="control-label"></label>
        <select asp-for="ColorId" asp-items="Model.Colors" class="form-control"></select>
        <span asp-validation-for="ColorId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <span class="required">*</span>
        <label asp-for="FabricId" class="control-label"></label>
        <select asp-for="FabricId" asp-items="Model.Fabrics" class="form-control"></select>
        <span asp-validation-for="FabricId" class="text-danger"></span>
    </div>
  