Produccion/Produccion/Models/InventoryViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.Drawing;

namespace Produccion.Models
{
    public class InventoryViewModel
    {
        [Display(Name = "Consecutivo")]
        public int Id { get; set; }

        [Display(Name = "Cantidad")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:N2}")]
        public float Cantidad { get; set; }

        [Display(Name = "Color")]
        public int ColorId { get; set; }
        public IEnumerable<SelectListItem>? Colors { get; set; }

        [Display(Name = "Tipo tela")]
        public int FabricId { get; set; }
        public IEnumerable<SelectListItem>? Fabrics { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Debes de seleccionar un color y un tipo de tela.")]
        [Display(Name = "Materia Prima")]
        public int RawMaterialId { get; set; }        
        public IEnumerable<SelectListItem>? RawMaterials { get; set; }
    }
}

Produccion/Produccion/Controllers/InventoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Produccion.Data;
using Produccion.Data.Entities;
using Produccion.Helpers;
using Produccion.Models;
using Vereyon.Web;
using static Produccion.Helpers.ModalHelper;

namespace Produccion.Controllers
{
    public class InventoriesController : Controller
    {
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IFlashMessage _flashMessage;

        public InventoriesController(DataContext context, ICombosHelper combosHelper, IFlashMessage flashMessage)
        {
            _context = context;
            _combosHelper = combosHelper;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            List<Inventory> Inventory =            
                await _context.Inventories
                .Include(i => i.RawMaterial)
                .ThenInclude(r => r.Fabric)
                .Include(i => i.RawMaterial)
                .ThenInclude(r => r.Color)
                .OrderBy(i => i.Id)
                .ToListAsync();
            List<InventoryIndexViewModel> InventoryPartial = new();
            foreach (Inventory inventory in Inventory)
            {
                if(InventoryPartial.Count == 0)
                {                    
                    InventoryPartial.Add(new(){
                        RawMaterial = inventory.RawMaterial,
                        ExistenciaTotal = inventory.Existencia
                    });
                }
                else
                {
                    if (InventoryPartial.Any(i => i.RawMaterial.Id == inventory.RawMaterial.Id))
                    {
                        foreach (InventoryIndexViewModel rawMaterial in InventoryPartial)
                        {
                            if (rawMaterial.RawMaterial.Id == inventory.RawMaterial.Id)
                            {
                                rawMaterial.ExistenciaTotal += inventory.Existencia;
                            }

                        }
                    }
                    else
                    {
                        InventoryPartial.Add(new()
                        {
                            RawMaterial = inventory.RawMaterial,
                            ExistenciaTotal = inventory.Existencia
                        });
                    }                    
                }
            }
            
            return View(InventoryPartial);
        }
        public async Task<IActionResult> Details(int id)
        {
            List<Inventory> Inventory =
                await _context.Inventories
                .Include(i => i.RawMaterial)
                .ThenInclude(r => r.Fabric)
                .Include(i => i.RawMaterial)
                .ThenInclude(r => r.Color)
                .OrderBy(i => i.Id)
                .ToListAsync();
            List<Inventory> InventoryDetails = new();
            foreach (var inventory in Inventory)
            {
                if(inventory.RawMaterial.Id == id)
                {
                    InventoryDetails.Add(inventory);
                }
            }
            return View(InventoryDetails);
        }

        [NoDirectAccess]
        public async Task<IActionResult> AddOrEdit(int id)
        {
            InventoryViewModel model = new()
            {
                Colors = await _combosHelper.GetComboColorsAsync(),
                Fabrics = await _combosHelper.GetComboFabricsAsync(),
                RawMaterials = await _combosHelper.GetComboRawMaterialsAsync(0),
                Cantidad = 0
            };
            if (id == 0)
            {
                return View(model);
            }
            else
            {
                Inventory inventory = await _context.Inventories
                .Include(r => r.RawMaterial)
                .ThenInclude(i => i.Color)
                .Include(i => i.RawMaterial)
                .ThenInclude(r => r.Fabric)
                .FirstOrDefaultAsync(r => r.Id == id);

                model = new()
                {
                    Id = inventory.Id,
                    Colors = await _combosHelper.GetComboColorsAsync(),
                    ColorId = inventory.RawMaterial.Color.Id,
                    Fabrics = await _combosHelper.GetComboFabricsAsync(),
                    FabricId = inventory.RawMaterial.Fabric.Id,
                    RawMaterials = await _combosHelper.GetComboRawMaterialsAsync(),
                    RawMaterialId = inventory.RawMaterial.Id,
                    Cantidad = inventory.Cantidad
                };

                return View(model);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit(int id, InventoryViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (id == 0)
                    {
                        Inventory inventory = new()
                        {
                            RawMaterial = await _context.RawMaterials
                                            .Include(r => r.Color)
                                            .Include(r => r.Fabric)
                                            .FirstOrDefaultAsync(r => r.Id == model.RawMaterialId),
                            Cantidad = model.Cantidad,
                            Existencia = model.Cantidad
                        };
                        _context.Add(inventory);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro creado");
                    }
                    else
                    {
                        Inventory inventory = new()
                        {
                            Id = model.Id,
                            RawMaterial = await _context.RawMaterials
                                            .Include(r => r.Color)
                                            .Include(r => r.Fabric)
                                            .FirstOrDefaultAsync(r => r.Id == model.RawMaterialId),
                            Cantidad = model.Cantidad,                            
                        };
                        _context.Update(inventory);
                        await _context.SaveChangesAsync();
                        _flashMessage.Info("Registro actualizado");
                    }
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Danger("Ya existe un registro con el mismo nombre.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                    return View(model);
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                    return View(model);
                }
                model.Colors = await _combosHelper.GetComboColorsAsync();
                model.Fabrics = await _combosHelper.GetComboFabricsAsync();
                model.RawMaterials = await _combosHelper.GetComboRawMaterialsAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);

        }

        [Authorize(Roles = "Admin")]
        [NoDirectAccess]
        public async Task<IActionResult> Delete(int? id)
        {
            Inventory inventory = await _context.Inventories
                .Include(r => r.RawMaterial)
                .FirstOrDefaultAsync(r => r.Id == id);
            try
            {
                _context.Inventories.Remove(inventory);
                await _context.SaveChangesAsync();
                _flashMessage.Info("Registro borrado.");

            }
            catch
            {
                _flashMessage.Danger("No se puede borrar el registro porque tiene datos relacionados.");

            }
            return RedirectToAction(nameof(Index));
        }

        public JsonResult GetRawMaterialColor(int colorId)
        {
            Color color = _context.Colors
                .Include(c => c.RawMaterials)
                .FirstOrDefault(c => c.Id == colorId);
            
            if (color == null)
            {
                return null;
            }

            return Json(color.RawMaterials.OrderBy(d => d.Nombre));
        }

        

    }
}

Produccion/Produccion/Views/Inventories/AddInventory.cshtml
@model Produccion.Models.InventoryViewModel

@{
    ViewData["Title"] = "AddInventory";
}
<flash dismissable="true" />

<h1>Agregar Inventario</h1>


<hr />
<div class="row text-light">
    <div class="col-md-4">
        <form asp-action="AddInventory">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ColorId" class="control-label"></label>
                <select asp-for="ColorId" asp-items="Model.Colors" class="form-control"></select>
                <span asp-validation-for="ColorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FabricId" class="control-label"></label>
                <select asp-for="FabricId" asp-items="Model.Fabrics" class="form-control"></select>
                <span asp-validation-for="FabricId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RawMaterialId" class="control-label"></label>
                <select asp-for="RawMaterialId" asp-items="Model.RawMaterials" class="form-control"></select>
                <span asp-validation-for="RawMaterialId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" type="number" step="0.01" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>

            </div>

            <div class="form-group mt-2">
                <input type="submit" value="Agregar" class="btn btn-dark" />
                <a asp-action="Index" class="btn btn-dark">Regresar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {
        $("#ColorId").change(function () {
            $("#RawMaterialId").empty();
            $("#RawMaterialId").append('<option value="0">[Selecciona un material...]</option>');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetRawMaterialColor")',
                dataType: 'json',
                data: { colorId: $("#ColorId").val() },
                success: function(rawMaterials) { 
                    $.each(rawMaterials, function (i, rawMaterial) {
                        $("#RawMaterialId").append('<option value="'
                            + rawMaterial.id + '">'
                            + rawMaterial.nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve rawMaterial.' + ex);
                }
            });
            return false;
        })
       
    });
    </script>
 }

Produccion/Produccion/Views/Inventories/AddOrEdit.cshtml
@model Produccion.Models.InventoryViewModel

@{
    ViewData["Title"] = "Agregar Inventario";    
}

<flash dismissable="true" />
<div class="row">
    <div class="col-md-6 offset-3">
        <div class="card bg-dark mb-3 " >
            <h3 class="panel-title text-light m-2"><i class="fa-solid fa-cart-flatbed"></i> Agregar Inventario</h3>
            <div class="container smfont bg-light">
                <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
                    <div class="box-body">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="ColorId" class="control-label"></label>
                            <select asp-for="ColorId" asp-items="Model.Colors" class="form-control"></select>
                            <span asp-validation-for="ColorId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="FabricId" class="control-label"></label>
                            <select asp-for="FabricId" asp-items="Model.Fabrics" class="form-control"></select>
                            <span asp-validation-for="FabricId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="RawMaterialId" class="control-label"></label>
                            <select asp-for="RawMaterialId" asp-items="Model.RawMaterials" class="form-control"></select>
                            <span asp-validation-for="RawMaterialId" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Cantidad" class="control-label"></label>
                            <input asp-for="Cantidad" type="number" step="0.01" class="form-control" />
                            <span asp-validation-for="Cantidad" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="submit" value="Agregar" class="btn btn-dark" />
                        <a asp-action="Index" class="btn btn-dark">Regresar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        $(document).ready(function () {
        $("#ColorId").change(function () {
            $("#RawMaterialId").empty();
            $("#RawMaterialId").append('<option value="0">[Selecciona un material...]</option>');
            $.ajax({
                type: 'POST',
                url: '@Url.Action("GetRawMaterialColor")',
                dataType: 'json',
                data: { colorId: $("#ColorId").val() },
                success: function(rawMaterials) { 
                    $.each(rawMaterials, function (i, rawMaterial) {
                        $("#RawMaterialId").append('<option value="'
                            + rawMaterial.id + '">'
                            + rawMaterial.nombre + '</option>');
                    });
                },
                error: function (ex) {
                    alert('Failed to retrieve rawMaterial.' + ex);
                }
            });
            return false;
        })
       
    });
    </script>
}

Produccion/Produccion/Views/Inventories/Details.cshtml
@model IEnumerable<Produccion.Data.Entities.Inventory>

@{
    ViewData["Title"] = "Detalles";
}
<flash dismissable="true" />



<div class="row">
    <div class="col-md-12">
        <div class="card bg-dark mb-3 " >
            <h3 class="panel-title text-light m-2"><i class="fa-solid fa-cart-flatbed"></i> Registro de Inventario</h3>
            <div class="panel panel-default bg-light">
            
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th>
                                Consecutivo
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Fabric)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Color)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Cantidad) 
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Existencia) 
                            </th>
                            @if (User.IsInRole("Admin"))
                                {
                                    <th>

                                    </th>
                                }
            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model){
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Fabric.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Color.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cantidad) m
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Existencia) m
                            </td>
                            @if (User.IsInRole("Admin"))
                                {
                                    <td>
                                        <a onclick="showInPopup('@Url.Action("AddOrEdit", "Inventories", new { id=item.Id }, Context.Request.Scheme)' , 'Editar Inventario')" class="btn btn-sm btn-warning"><i class="fa-solid fa-pen-to-square text-dark"></i> </a>
                                        <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                                    </td>
                                }
                        </tr>
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<partial name="_DeleteDialog" />

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Inventories/Delete/', false);
    </script>
}

Produccion/Produccion/Views/Inventories/Index.cshtml
@model IEnumerable<Produccion.Models.InventoryIndexViewModel>

@{
    ViewData["Title"] = "Inventario";
}
<flash dismissable="true" />
<div class="boton">
    <a asp-action="AddOrEdit" class="btn btn-dark mb-2"><i class="fa-solid fa-circle-plus"></i> Inventario</a>    
</div>

<div class="row">
    <div class="col-md-12">
        <div class="card bg-dark mb-3 " >
            <h3 class="panel-title text-light m-2"><i class="fa-solid fa-cart-flatbed"></i> Inventario</h3>
            <div class="panel panel-default bg-light">
            
                <table class="table table-hover table-responsive table-striped" id="MyTable">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Fabric)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.RawMaterial.Color)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.ExistenciaTotal)
                            </th>
                            
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model){
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Id)
                            </td>
                            <td>
                                <a asp-action="Details" asp-route-id="@item.RawMaterial.Id"><i class="fa-solid fa-circle-info"></i> @Html.DisplayFor(modelItem => item.RawMaterial.Nombre)</a>
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Fabric.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.RawMaterial.Color.Nombre)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ExistenciaTotal) m
                            </td>                            
                        </tr>
                }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header bg-dark">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<partial name="_DeleteDialog" />


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    
    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#MyTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>


    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Inventories/Delete/', false);
    </script>
}